### ISSUE TITLE
Your question about SciDB

### ISSUE THREAD

**Issue by ventz** [pranasblk/Hello-World#1]
@pranasblk - Could not find any contact info for you, so using this poor method to get in touch

Posted a reply to your question with info:
https://hub.docker.com/r/cerbo/scidb/

Feel free to delete this.

**Comment by pranasblk** [comment]
I believe everyone on the Docker Hub would like to see the link. 
Would you mind either adding link to README or even better configuring Docker Hub to build image from GitHub?

e.g. https://hub.docker.com/r/pranasblk/devopsgit/~/dockerfile/ (this one using BitBucket)

**Comment by ventz** [comment]
Hi - Added it on Docker Hub already (in comments, for you) and on the main page under:

How to build your own Cerbo SciDB Docker image:
https://github.com/cerbo/cerbo-scidb

If you don't mind, send us an email to "support@cerbo.io" and i'll reply there just so that we are not using this issue tracker for communication :)

You can delete the thread.

**Comment by ventz** [comment]
Follow up about DockerHub<->GitHub auto build - as of right now, the install provided by P4 is not clean enough where this can be fully automated into an automated Dockerfile build. There are many steps where human input is required.
